---

dependencies: []

galaxy_info:
  author: klen
  company: Stouts
  description: Manage supervisor
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - development
  - system
