---

supervisor_tasks:
  - name: springboot
    command: "{{ springboot_command }}"
    autostart: true
    autorestart: true
newrelic_license_key: "{{ new_relic_key }}"
newrelic_service_state: started
environment_config:
  PRIVATE_DOMAIN: "{{ private_domain }}"