spring:
  application:
    name: micro1

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: sampleadmin
    password: 654321
  jpa:
     show-sql: true
     hibernate:
      ddl-auto: validate

server:
  port: 8070