spring:
  application:
    name: users
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://wiseman.cgholfkyyxdg.us-east-1.rds.amazonaws.com:3306/microservices
    username: micro
    password: 123456
  jpa:
     show-sql: true
     hibernate:
      ddl-auto: validate

server:
  port: 8070

endpoints:
  beans:
    sensitive: false