---

- name: Install jq
  apt: name=jq

- name: install boto
  pip: name=boto

- name: Install awscli
  pip: name=awscli

- name: Get ssh id
  shell: aws s3api head-object --bucket {{ ssh_bucket }} --key {{ ssh_user }} | jq '.Metadata.sshid'
  register: iam_user_ssh_id

- name: Download private ssh key
  s3: bucket={{ ssh_bucket }} object={{ ssh_user }} dest=/root/.ssh/codecommit_rsa mode=get

- name: chmod ssh key
  file: path=/root/.ssh/codecommit_rsa mode=600

- name: Configure ssh config file
  template: src=config.j2 dest=/root/.ssh/config owner=root mode=600